apiVersion: velero.io/v1
kind: Backup
metadata:
  name: kyma-backup
  namespace: kyma-system
spec:
  includedNamespaces:
  - '*'
  includedResources:
  - '*'
  excludedResources:
  - natsschannels.messaging.knative.dev
  - subscriptions.eventing.knative.dev
  - channels.eventing.knative.dev
  includeClusterResources: true
  storageLocation: default
  volumeSnapshotLocations: 
  - default
